# Generated by Django 4.0.4 on 2022-05-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='file',
            field=models.FileField(upload_to='bank_statements'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
