# Generated by Django 4.0.4 on 2022-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0002_alter_bankstatement_file_alter_bankstatement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
