# Generated by Django 4.0.4 on 2022-05-14 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0004_alter_bankstatement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='upload_date',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
