# Generated by Django 4.0.4 on 2022-05-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0005_bankstatement_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='content_inserted_into_database',
            field=models.DateField(blank=True, null=True),
        ),
    ]
