# Generated by Django 4.0.4 on 2022-05-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'bank_account_statements',
            '0006_bankstatement_content_inserted_into_database',
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankStatement',
            new_name='Statement',
        ),
    ]
