# Generated by Django 4.0.4 on 2022-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0007_rename_bankstatement_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='file',
            field=models.FileField(max_length=500, upload_to='bank_statements'),
        ),
    ]
