# Generated by Django 4.0.4 on 2022-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0009_rename_date_modified_statement_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
