# Generated by Django 4.0.4 on 2022-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0010_statement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='filename_date_format',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='statement',
            name='file',
            field=models.FileField(
                max_length=500, unique=True, upload_to='bank_statements'
            ),
        ),
    ]
