# Generated by Django 4.0.4 on 2022-05-14 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0011_bank_filename_date_format_alter_statement_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='filename_date_format',
        ),
    ]
