# Generated by Django 4.0.4 on 2022-05-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0012_remove_bank_filename_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='filename_date_format',
            field=models.CharField(
                choices=[('fr', 'Jours Mois'), ('en', 'Mois Jours')],
                default='fr',
                max_length=2,
            ),
        ),
    ]
