# Generated by Django 4.0.4 on 2022-05-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0013_bank_filename_date_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='upload_date',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='bank',
            name='filename_date_format',
            field=models.CharField(
                choices=[('fr', 'Jours / Mois'), ('en', 'Mois / Jours')],
                default='fr',
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='statement',
            name='file',
            field=models.FileField(
                max_length=500, upload_to='bank_statements'
            ),
        ),
        migrations.AlterField(
            model_name='statement',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
