# Generated by Django 4.0.4 on 2022-05-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0014_rename_upload_date_statement_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='content_inserted_into_database',
        ),
    ]
