# Generated by Django 4.0.4 on 2022-05-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'bank_account_statements',
            '0015_remove_statement_content_inserted_into_database',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='name',
        ),
    ]
