# Generated by Django 4.0.4 on 2022-05-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0017_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(
                choices=[
                    ('Crédit Mutuel', 'Crédit Agricole'),
                    ('Crédit Agricole', 'Crédit Agricole'),
                ],
                default='Crédit Agricole',
                max_length=15,
                unique=True,
            ),
        ),
    ]
