# Generated by Django 4.0.4 on 2022-05-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0004_periodicity'),
        (
            'bank_account_statements',
            '0020_statement_category_statement_periodicity',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='periodicity',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='categorization.category',
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='periodicity',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='categorization.periodicity',
            ),
        ),
    ]
