# Generated by Django 4.0.4 on 2022-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'bank_account_statements',
            '0022_remove_transaction_category_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
