# Generated by Django 4.0.4 on 2022-05-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0025_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
