# Generated by Django 4.0.4 on 2022-05-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0029_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
