# Generated by Django 4.0.4 on 2022-05-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0016_delete_transactiondata'),
        ('bank_account_statements', '0036_remove_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categorization.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='extended_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
