# Generated by Django 4.0.4 on 2022-05-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0038_alter_transaction_extended_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='custom_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='extended_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
