# Generated by Django 4.0.4 on 2022-05-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0039_transaction_custom_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['-date', 'bank']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', 'label']},
        ),
    ]
