# Generated by Django 4.0.4 on 2022-06-05 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account_statements', '0042_alter_transaction_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_account_statements.statement'),
        ),
    ]
