# Generated by Django 4.0.4 on 2022-05-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0004_periodicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Periodicity',
        ),
        migrations.AddField(
            model_name='category',
            name='category_keywords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorization.categorykeywords'),
        ),
    ]
