# Generated by Django 4.0.4 on 2022-05-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            'categorization',
            '0005_categorykeywords_delete_periodicity_and_more',
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_keywords',
        ),
        migrations.AddField(
            model_name='categorykeywords',
            name='category_keywords',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='categorization.category',
            ),
        ),
    ]
