# Generated by Django 4.0.4 on 2022-05-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0008_rename_keyword_categorykeywords_keyword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryKeywords',
            new_name='CategoryKeyword',
        ),
    ]
