# Generated by Django 4.0.4 on 2022-05-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0009_rename_categorykeywords_categorykeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorykeyword',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='categorization.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorykeyword',
            name='keyword',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
