# Generated by Django 4.0.4 on 2022-05-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorykeyword',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
