# Generated by Django 4.0.4 on 2022-05-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0014_transactiondata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiondata',
            old_name='my_data',
            new_name='transaction',
        ),
    ]
