# Generated by Django 4.0.4 on 2022-05-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0015_rename_my_data_transactiondata_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionData',
        ),
    ]
