# Generated by Django 4.0.4 on 2022-05-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0017_alter_categorykeyword_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
