# Generated by Django 4.0.4 on 2022-05-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0018_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorykeyword',
            options={'ordering': ['keyword']},
        ),
    ]
