# Generated by Django 4.0.4 on 2022-06-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorization', '0019_alter_categorykeyword_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='transactions_are_fixed_monthly_costs',
            field=models.BooleanField(default=False),
        ),
    ]
